name: Debug CI
on:
  workflow_call:
  push:
    branches:
      - 'branch-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: |
          git show --format=fuller HEAD
