name: Debug CI
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
  push:
    branches:
      - 'branch-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "${{inputs.ref || github.ref }}"
      - name: Run a one-line script
        run: |
          git show --format=fuller HEAD
